export default [
  {
    year: 2012,
    id: 'hester',
    name: 'Jacob Hester',
    position: 'FB',
    team: 'Denver Broncos',
    manager: 'Gerald Siiiiiiiibon',
  },
  {
    year: 2013,
    id: 'charles',
    name: 'Jamaal Charles',
    position: 'RB',
    team: 'Kansas City Chiefs',
    manager: 'Hailvern',
  },
  {
    year: 2014,
    id: 'sanchez',
    name: 'Mark Sanchez',
    position: 'QB',
    team: 'Philadelphia Eagles',
    manager: 'Manziels Two Headed Unicorn',
  },
  {
    year: 2015,
    id: 'lacy',
    name: 'Eddie Lacy',
    position: 'RB',
    team: 'Green Bay Packers',
    manager: 'Wolverhampton Wasters',
  },
  {
    year: 2016,
    id: 'mariota',
    name: 'Marcus Mariota',
    position: 'QB',
    team: 'Tennessee Titans',
    manager: 'Tha Dollar',
  },
  {
    year: 2017,
    id: 'gurley',
    name: 'Todd Gurley',
    position: 'RB',
    team: 'LA Rams',
    manager: 'Si2on',
  },
  {
    year: 2018,
    id: 'robby',
    name: 'Robby Anderson',
    position: 'WR',
    team: 'New York Jets',
    manager: 'Kansas City Chumps',
  },
  {
    year: 2019,
    id: 'kelce',
    name: 'Travis Kelce',
    position: 'TE',
    team: 'Kansas City Chiefs',
    manager: 'Kansas City Chumps',
  },
  {
    year: 2020,
    id: 'waller',
    name: 'Darren Waller',
    position: 'TE',
    team: 'LA Raiders',
    manager: 'Catch-22',
  },
];
